Fixed #imports to be compatible with Xcode 7.1
A framework's header files can no longer import other own header files using
angular import syntax (#import <ReactiveCocoa/…>) as of Xcode 7.1. That leads to
a lot errors when importing (not compiling) this framework.

Example:

```
ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:67:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
import <ReactiveCocoa/EXTKeyPathCoding.h>
```

Properly using #import "XYZ.h" instead of #import <ReactiveCocoa/XYZ.h> fixes this issue.